### ISSUE TITLE
Empty password shown as allowed

### ISSUE THREAD

**Issue by x43x61x69** [ryanries/PassFiltEx#15]
The `PasswordIsOK = FALSE;` seems missing from the above section, which will make empty password shown as "allowed":

https://github.com/ryanries/PassFiltEx/blob/80734d829ff390f4c2cb1b5dbb405207a0d8d779/PassFiltEx.c#L508

Or it's done this way so the Admin can actually set the password as empty on purpose?

**Comment by ryanries** [comment]
Good catch. I will fix it shortly. Thank you!

**Comment by ryanries** [comment]
Fixed
