### ISSUE TITLE
Custom error message

### ISSUE THREAD

**Issue by juangranados** [ryanries/PassFiltEx#16]
Hi Ryan! Thanks for your amazing password filter. I was able to deploy it on my environment and works flawlessly.
I would like to customize the error message that DC server returns to the users. Would it be possible with PassFiltEx?

Best regards.

**Comment by ryanries** [comment]
Unfortunately this is just not possible. People have been wanting this for years, but the only way to implement this currently is to have an agent on the workstation that does the policy checking and displays the custom error message to the user. The DC is hard-coded to return only one or two different error messages to the client when a password change fails.
