### ISSUE TITLE
Add such a group: require lower OR require upper

### ISSUE THREAD

**Issue by nikimaxim** [ryanries/PassFiltEx#17]
Hello
Add such a group: require lower OR require upper
Example:  require lower OR require upper AND require digit
Thank You.

**Comment by nikimaxim** [comment]
?

**Comment by ryanries** [comment]
Sorry, just now seeing this. Yes I will consider it and start working on it. Should be pretty easy.

**Comment by nikimaxim** [comment]
Thank You.

**Comment by nikimaxim** [comment]
@ryanries Is it worth waiting in the near future?

**Comment by nikimaxim** [comment]
@ryanries ?

**Comment by ryanries** [comment]
@nikimaxim Hey I finally added this in the latest push. It's 0n32 in RequireCharClasses. :)
