### ISSUE TITLE
We can't reset krbtgt_xxxxx passwords for RODC

### ISSUE THREAD

**Issue by rgarrigues** [ryanries/PassFiltEx#18]
Hello Ryan,
Like previous closed case https://github.com/ryanries/PassFiltEx/issues/11 
we can't reset krbtgt_xxxxx passwords (KRBTGT accounts for RODCs).
Do you have a workaround except "disabling PassFiltEx" during reset process (which involves 2 DC reboots......) ?

**Comment by ryanries** [comment]
Ohh, good find. That's a bug. Let me work on that.

**Comment by ryanries** [comment]
@rgarrigues This should now be fixed in v1.1.9. Find it on the Releases tab. Please confirm that it's fixed. Thanks.

**Comment by rgarrigues** [comment]
Thank you very much !! we will install this new version and test as soon as possible. I'll keep you advised.

**Comment by rgarrigues** [comment]
After installing version 1.1.9, krbtgt_xxxxx password reset worked like a charm without disabling PassFiltEx !
Thank you for the great job.

**Comment by solardiz** [comment]
FWIW, looks like PassFiltEx currently checks for "krbtgt" as case-insensitive, but for the "krbtgt_" prefix as case-sensitive. I guess this discrepancy is unintentional, but is no problem, and a case-sensitive check for both (thus, only working for all-lowercase) would also have been sufficient (but is probably not recommended)?

```c
        if (_wcsicmp(AccountNameCopy, L"krbtgt") == 0)
        {
                EventWriteStringW2(L"[%s:%s@%d] Always allowing password change for krbtgt account.", __FILENAMEW__, __FUNCTIONW__, __LINE__);

                goto End;
        }

        if (wcsncmp(L"krbtgt_", AccountNameCopy, wcslen(L"krbtgt_")) == 0)
        {
                EventWriteStringW2(L"[%s:%s@%d] Always allowing password change for RODC krbtgt account.", __FILENAMEW__, __FUNCTIONW__, __LINE__);

                goto End;
        }
```

**Comment by ryanries** [comment]
Hmm yes I would probably say this was unintentional. Ideally I would stay consistent and do all comparisons the same way. But in this case, I don't think it matters much. If someone in your domain is making copy-cat krbtgt... or KrBtGt accounts... you have more urgent problems!
