### ISSUE TITLE
no dll in v1.19

### ISSUE THREAD

**Issue by 8spoon9** [ryanries/PassFiltEx#20]
Hello,

There doesn't appear to be a .dll in the most recent release. It is present in previous releases.

**Comment by ryanries** [comment]
It's there?

![image](https://user-images.githubusercontent.com/5650163/105107677-336b9600-5a7e-11eb-9dac-ef7741c242a4.png)

**Comment by 8spoon9** [comment]
am idiot. i had downloaded the master which didn't have the .dll. please disregard.
