### ISSUE TITLE
Character Class Requirement

### ISSUE THREAD

**Issue by NWarila** [ryanries/PassFiltEx#24]
Is there any interest to allow a code submission to enable a per-character class requirement in addition to the word blacklist? This is an unachievable policy requirement for a ton of organizations, mostly those who do contract work for various government entities and to date I have never found a solid solution to meet this requirement. 

I personally do not have the skillset to do this, but if there is a willingness to allow a pull request to add these features I am willing to either compensate you directory (if you want) or look for a 3rd party to commit to this repo. Wanted to ensure I had your blessing before going down that route. 

I will also build a admx/adml file to compliment the new functionality.

**Comment by OftKilted** [comment]
If you’re following the [NIST 800-63b (version 3)](https://pages.nist.gov/800-63-3/sp800-63b.html#sec5) guidance for memorized secret verifiers then per-character class requirements gets wonky.

**Comment by NWarila** [comment]
The actual requirements placed on the organizations I tend to service are as follows:
- Minimum of 2 characters of the lowercase class.
- Minimum of 2 characters of the uppercase class.
- Minimum of 2 characters of the number class.
- Minimum of 2 characters of the special character class.
- Minimum password length of 12 characters (MS already does this)
- Maximum of 3 consecutive characters of the same character class.*

* This tends to get a blanket waiver as it pushes users to use pattern-based passwords instead of more robust ones.

**Comment by ryanries** [comment]
@NWarila Interesting proposal. I haven't considered it before. I'm thinking about it.

**Comment by NWarila** [comment]
@ryanries awesome! Like I said, I am willing to support you or get the code written elsewhere and commit to this repo, just wanted to make sure I wasn't moving the project into a direction you weren't intending. If you decide otherwise, I would like permission to fork the project.

**Comment by ryanries** [comment]
@NWarila I have published a new release, https://github.com/ryanries/PassFiltEx/releases/tag/v1.2.20, that removes the 'RequireCharClasses' reg setting and replaces it with new reg settings MinLower/MinUpper/MinDigit/MinSpecial/MinUnicode. I updated the documentation in the readme as well. I believe this will help you achieve every one of the requirements you listed in your bullet points above except for the very last one. Let me know if that final bullet point is still really important to you before I invest more effort in it.

Also please give the PassFiltExTest.exe program a try and make sure all the rules are working as you'd expect them to. Thanks!
