### ISSUE TITLE
If the blacklist reloading interval questions.

### ISSUE THREAD

**Issue by poplarfeng** [ryanries/PassFiltEx#27]
The blacklist is reloaded every 60 seconds, so feel free to edit the blacklist file at will. The password filter will read the new updates within a minute.

//
 1. If the blacklist reloading interval can be modified？
  2. If the blacklist file is not changed, will it be reloaded?

thank a lot.

**Comment by ryanries** [comment]
Hello,

1. No, currently the reloading frequency is hard coded at 60 seconds.
2. No, the file is not reloaded if it did not change. I monitor for last modified time specifically and only reload when that changes.

Thanks!

**Comment by poplarfeng** [comment]
> Hello,
> 
> 1. No, currently the reloading frequency is hard coded at 60 seconds.
> 2. No, the file is not reloaded if it did not change. I monitor for last modified time specifically and only reload when that changes.
> 
> Thanks!

Thank you vevy much for your answer.
